server:
  port: 8080
  servlet:
    context-path: /suggestion
spring:
  datasource:
    url: jdbc:dm://localhost:5236/SUGGES
    driver-class-name: dm.jdbc.driver.DmDriver
    username: SUGGES
    password: 1234567890
    # hikaril连接池配置
    hikari:
      #客户端等待连接池连接的最大毫秒数
      connection-timeout: 20000
      #连接池中维护的最小空闲连接数
      minimum-idle: 5
      #连接池中最多连接数
      maximum-pool-size: 30
      #允许连接在连接池中空闲的最长时间（以毫秒为单位）
      idle-timeout: 300000
      #池中连接关闭后的最长生命周期（以毫秒为单位）
      max-lifetime: 1200000
      #返回的连接是否自动提交
      auto-commit: false
    type: dm.jdbc.pool.DmdbDataSource

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    servlet:
      content-type: text/html

  jmx:
    default-domain: suggestion
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html



#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  #起别名，写sql语句时，返回类型不用复杂的写成类的全路径名，直接写成类名（不区分大小写）
  typeAliasesPackage: com.css.aq.base.**.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true

